version: "3"

vars:
  TF_STATE_DIR: "{{ .TASKFILE_DIR }}/tf_states"
  K8S_CONTEXT_DIR: "{{ .TASKFILE_DIR }}/contexts"
  T01_DIR: "{{ .TASKFILE_DIR }}/01_clusters"
  T02_DIR: "{{ .TASKFILE_DIR }}/02_core_services"
  T03_DIR: "{{ .TASKFILE_DIR }}/03_core_config"

tasks:
  clusters:
    desc: Provision Kind Clusters
    dir: "{{ .T01_DIR }}"
    cmds:
      - terraform init && terraform apply -auto-approve
    sources:
      - "{{ .T01_DIR }}/**/*"
    generates:
      - "{{ .TF_STATE_DIR }}/01_clusters.tfstate"
      - "{{ .K8S_CONTEXT_DIR }}/kubeconfig"

  core_services:
    desc: Provision core services on clusters
    dir: "{{ .T02_DIR }}"
    cmds:
      - terraform init && terraform apply -auto-approve
    sources:
      - "{{ .T02_DIR }}/**/*"
      - "{{ .TF_STATE_DIR }}/01_clusters.tfstate"
    generates:
      - "{{ .TF_STATE_DIR }}/02_core_services.tfstate"

  core_config:
    desc: Configure core services on clusters
    dir: "{{ .T03_DIR }}"
    cmds:
      - terraform init && terraform apply -auto-approve
    sources:
      - "{{ .T03_DIR }}/**/*"
      - "{{ .TF_STATE_DIR }}/01_clusters.tfstate"
      - "{{ .TF_STATE_DIR }}/02_core_services.tfstate"
    generates:
      - "{{ .TF_STATE_DIR }}/03_core_config.tfstate"

  in-network:
    desc: Run docker container inside the Kind in-network
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - docker-compose -f docker/docker-compose.yml run --rm utils sh -c '{{ .CLI_ARGS }}'

  reset:
    desc: Remove everything
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - rm {{ .TF_STATE_DIR }}/* || true
      - rm {{ .K8S_CONTEXT_DIR }}/* || true
      - rm -rf {{ .T01_DIR }}/.terraform || true
      - rm -rf {{ .T02_DIR }}/.terraform || true
      - rm -rf {{ .T03_DIR }}/.terraform || true
      - kind delete clusters -A

  k9s:
    desc: Start k9s with the generated contexts
    cmds:
      - KUBECONFIG={{ .K8S_CONTEXT_DIR }}/kubeconfig k9s

  all:
    desc: Provision the full stack
    cmds:
      - task: clusters
      - task: core_services
      - task: core_config
