version: "3.7"
services:
  utils:
    build:
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ..:/work
    working_dir: /work
    networks:
      - kind
    environment:
      - KUBECONFIG=/work/contexts/incluster_kubeconfig

networks:
  kind:
    name: kind
    external: true